# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "RTK"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "PIXHAWK" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["GPS", "RTK"]

heading_estimators:
  active: ["PIXHAWK", "GYRO", "COMPASS"]

lateral:
  R:
    vel_mavros: [0.1]
